/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_tum_uc_jvm_utility_MemoryAddress */

#ifndef _Included_edu_tum_uc_jvm_utility_MemoryAddress
#define _Included_edu_tum_uc_jvm_utility_MemoryAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_tum_uc_jvm_utility_MemoryAddress
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_tum_uc_jvm_utility_MemoryAddress_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     edu_tum_uc_jvm_utility_MemoryAddress
 * Method:    getObjectAddress
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_edu_tum_uc_jvm_utility_MemoryAddress_getObjectAddress
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
