/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_tum_uc_jvm_utility_MemoryAddress */
#include <stdio.h>
#include "edu_tum_uc_jvm_utility_MemoryAddress.h"

/*
 * Class:     edu_tum_uc_jvm_utility_MemoryAddress
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_tum_uc_jvm_utility_MemoryAddress_sayHello(JNIEnv *env, jobject thisObj){
	printf("Hello World\n");
	return;
}

JNIEXPORT jlong JNICALL Java_edu_tum_uc_jvm_utility_MemoryAddress_getObjectAddress
  (JNIEnv *env, jobject thisObj, jobject targetObj){
	jlong _return = (jlong)&targetObj;

	return _return;
}
